package com.duanHaiTao.dongLiYunKe.utils;

import com.auth0.jwt.interfaces.DecodedJWT;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

class JwtUtilTest {

    @Test
    public void testGetToken() {
        Map<String, String> map = new HashMap<>();
        map.put("username", "duan");
        map.put("age","12");
        String token = JwtUtil.getToken(map);
        System.out.println(token);
    }

    @Test
    public void testVerifyToken() {
        DecodedJWT decodedJWT = JwtUtil.verifyToken("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDc2NzIzMTQsInVzZXIiOiJ7XCJpZFwiOjEsXCJsb2dpbkFjdFwiOlwiYWRtaW5cIixcImxvZ2luUHdkXCI6XCJcIixcIm5hbWVcIjpcIueuoeeQhuWRmFwiLFwicGhvbmVcIjpcIjEzNzAwMDAwMDAwXCIsXCJlbWFpbFwiOlwiYWRtaW5AcXEuY29tXCIsXCJhY2NvdW50Tm9FeHBpcmVkXCI6MSxcImNyZWRlbnRpYWxzTm9FeHBpcmVkXCI6MSxcImFjY291bnROb0xvY2tlZFwiOjEsXCJhY2NvdW50RW5hYmxlZFwiOjEsXCJjcmVhdGVUaW1lXCI6MTY3NzAyOTgzMjAwMCxcImNyZWF0ZUJ5XCI6bnVsbCxcImVkaXRUaW1lXCI6MTY4NDc3MjQ2NjAwMCxcImVkaXRCeVwiOm51bGwsXCJsYXN0TG9naW5UaW1lXCI6MTcwMjIxNDMzOTAwMCxcInJvbGVzXCI6W3tcImlkXCI6MSxcInJvbGVcIjpcImFkbWluXCIsXCJyb2xlTmFtZVwiOm51bGx9XSxcImF1dGhvcml0aWVzXCI6W3tcImF1dGhvcml0eVwiOlwiYWRtaW5cIn0se1wiYXV0aG9yaXR5XCI6XCJhY3Rpdml0eTpsaXN0XCJ9LHtcImF1dGhvcml0eVwiOlwiYWN0aXZpdHk6YWRkXCJ9LHtcImF1dGhvcml0eVwiOlwiYWN0aXZpdHk6ZWRpdFwifSx7XCJhdXRob3JpdHlcIjpcImFjdGl2aXR5OnZpZXdcIn0se1wiYXV0aG9yaXR5XCI6XCJhY3Rpdml0eTpkZWxldGVcIn0se1wiYXV0aG9yaXR5XCI6XCJhY3Rpdml0eTpzZWFyY2hcIn0se1wiYXV0aG9yaXR5XCI6XCJjbHVlOmxpc3RcIn0se1wiYXV0aG9yaXR5XCI6XCJjbHVlOmFkZFwifSx7XCJhdXRob3JpdHlcIjpcImNsdWU6ZWRpdFwifSx7XCJhdXRob3JpdHlcIjpcImNsdWU6dmlld1wifSx7XCJhdXRob3JpdHlcIjpcImNsdWU6ZGVsZXRlXCJ9LHtcImF1dGhvcml0eVwiOlwiY2x1ZTppbXBvcnRcIn0se1wiYXV0aG9yaXR5XCI6XCJjdXN0b21lcjpsaXN0XCJ9LHtcImF1dGhvcml0eVwiOlwiY3VzdG9tZXI6dmlld1wifSx7XCJhdXRob3JpdHlcIjpcImN1c3RvbWVyOmV4cG9ydFwifSx7XCJhdXRob3JpdHlcIjpcInRyYW46bGlzdFwifSx7XCJhdXRob3JpdHlcIjpcInRyYW46dmlld1wifSx7XCJhdXRob3JpdHlcIjpcInByb2R1Y3Q6bGlzdFwifSx7XCJhdXRob3JpdHlcIjpcInByb2R1Y3Q6YWRkXCJ9LHtcImF1dGhvcml0eVwiOlwicHJvZHVjdDplZGl0XCJ9LHtcImF1dGhvcml0eVwiOlwicHJvZHVjdDp2aWV3XCJ9LHtcImF1dGhvcml0eVwiOlwicHJvZHVjdDpkZWxldGVcIn0se1wiYXV0aG9yaXR5XCI6XCJkaWN0eXBlOmxpc3RcIn0se1wiYXV0aG9yaXR5XCI6XCJkaWN0eXBlOmFkZFwifSx7XCJhdXRob3JpdHlcIjpcImRpY3R5cGU6ZWRpdFwifSx7XCJhdXRob3JpdHlcIjpcImRpY3R5cGU6dmlld1wifSx7XCJhdXRob3JpdHlcIjpcImRpY3R5cGU6ZGVsZXRlXCJ9LHtcImF1dGhvcml0eVwiOlwiZGljdmFsdWU6bGlzdFwifSx7XCJhdXRob3JpdHlcIjpcImRpY3ZhbHVlOmFkZFwifSx7XCJhdXRob3JpdHlcIjpcImRpY3ZhbHVlOmVkaXRcIn0se1wiYXV0aG9yaXR5XCI6XCJkaWN2YWx1ZTp2aWV3XCJ9LHtcImF1dGhvcml0eVwiOlwiZGljdmFsdWU6ZGVsZXRlXCJ9LHtcImF1dGhvcml0eVwiOlwidXNlcjpsaXN0XCJ9LHtcImF1dGhvcml0eVwiOlwidXNlcjphZGRcIn0se1wiYXV0aG9yaXR5XCI6XCJ1c2VyOmVkaXRcIn0se1wiYXV0aG9yaXR5XCI6XCJ1c2VyOnZpZXdcIn0se1wiYXV0aG9yaXR5XCI6XCJ1c2VyOmRlbGV0ZVwifSx7XCJhdXRob3JpdHlcIjpcInN5c3RlbTpsaXN0XCJ9LHtcImF1dGhvcml0eVwiOlwic3lzdGVtOmFkZFwifSx7XCJhdXRob3JpdHlcIjpcInN5c3RlbTplZGl0XCJ9LHtcImF1dGhvcml0eVwiOlwic3lzdGVtOnZpZXdcIn0se1wiYXV0aG9yaXR5XCI6XCJzeXN0ZW06ZGVsZXRlXCJ9XSxcImVuYWJsZWRcIjp0cnVlLFwicGFzc3dvcmRcIjpcIlwiLFwidXNlcm5hbWVcIjpcImFkbWluXCIsXCJhY2NvdW50Tm9uTG9ja2VkXCI6dHJ1ZSxcImNyZWRlbnRpYWxzTm9uRXhwaXJlZFwiOnRydWUsXCJhY2NvdW50Tm9uRXhwaXJlZFwiOnRydWV9In0._GQC2c-sku_8FEBuLJOXz009cBg7_f8o5gFL4mcuR_g");
        String string = decodedJWT.getClaim("user").asString();
        System.out.println(string);
        System.out.println(decodedJWT.getSignature().describeConstable());
    }
}